export const mySkills = [
  { title: "Tailwind CSS", icon: "tailwind" },
  { title: "shadcn/ui", icon: "shadcn" },
  { title: "Material UI", icon: "MaterialUIIcon" },
  { title: "Framer Motion", icon: "FramerMotionIcon" },
  { title: "JavaScript", icon: "javascript" },
  { title: "TypeScript", icon: "typescript" },
  { title: "ReactJS", icon: "react" },
  { title: "React Query", icon: "ReactQueryIcon" },
  { title: "Redux", icon: "ReduxIcon" },
  { title: "NextJS", icon: "nextjs" },
  { title: "NodeJS", icon: "nodejs" },
  { title: "ExpressJS", icon: "express" },
  { title: "MongoDB", icon: "mongodb" },
  { title: "PostgreSQL", icon: "PostgreSQLIcon" },
  { title: "Supabase", icon: "SupabaseIcon" },
  { title: "Prisma", icon: "PrismaIcon" },
  { title: "GraphQL", icon: "GraphQLIcon" },
  { title: "Docker", icon: "docker" },
  { title: "Vercel", icon: "vercel" },
  { title: "Git", icon: "git" },
  { title: "GitHub", icon: "gitHub" },
  { title: "ESLint", icon: "ESLintIcon" },
  { title: "Postman", icon: "postman" },
  { title: "npm", icon: "npm" },
];