
export const mySkills = [
  { title: "Java", icon: "_java" },
  { title: "JEE", icon: "_java1" },
  { title: "Spring", icon: "_java2" },
  { title: "Spring Boot", icon: "_java3" },
  { title: "HTML", icon: "_html" },
  { title: "CSS", icon: "_css" },
  { title: "JavaScript", icon: "_javascript" },
  { title: "TypeScript", icon: "_typescript1" },
  { title: "Angular", icon: "_typescript2" },
  { title: "Vue 3", icon: "_typescript3" },
  { title: "ExtJS", icon: "_typescript4" },
  { title: "Tailwind CSS", icon: "_tailwind" },
  { title: "Material UI", icon: "_MaterialUIIcon" },
  { title: "Ag-Grid", icon: "_MaterialUIIcon1" },
  { title: "NodeJS", icon: "_nodejs" },
  { title: "PostgreSQL", icon: "_mongodb" },
  { title: "Oracle", icon: "_mongodb1" },
  { title: "MySql", icon: "_mongodb2" },
  { title: "Mongodb", icon: "_mongodb3" },
  { title: "Docker", icon: "_docker" },
  { title: "Git", icon: "_git" },
  { title: "GitHub", icon: "_gitHub" },
  { title: "Bitbucket", icon: "_gitHub1" },
  { title: "Postman", icon: "_postman" },
  { title: "Jasper", icon: "_postman1" },
  { title: "Talend", icon: "_postman2" },
  { title: "PowerBI", icon: "_npm" },
  { title: "Splunk", icon: "_npm2" },
  { title: "Jenkins", icon: "_npm1" },
  { title: "Apache Tomcat", icon: "_vercel" },
  { title: "Jboss", icon: "_angular"},
  { title: "Glassfish", icon: "_Vue"},
  { title: "Kafka/RabbitMQ", icon: "_extjs"},
  { title: "Mailgun", icon: "_aws"},
  { title: "Junit", icon: "_aws1"},
];